# fly.toml app configuration file generated for gamingapp on 2025-06-07T17:40:51+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file. #

app = 'gamingapp'
primary_region = 'syd'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[processes]
  app = './bin/rails server'
  sidekiq = 'bundle exec sidekiq'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '30s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1

# Sidekiq gets 8GB for transcription (needs 4 CPUs for 8GB)
[[vm]]
  memory = '8gb'
  cpu_kind = 'performance'
  cpus = 4
  processes = ['sidekiq']

[env]
  RAILS_LOG_LEVEL = "info"
  RAILS_SERVE_STATIC_FILES = "true"

[[mounts]]
  source = "video_storage"
  destination = "/video_storage"
  processes = ["sidekiq"]

swap_size_mb = 2048

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'